server:
  port: 8113

spring:
  application:
    name: inventory-transfer-agent-4j
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_transfer?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:8b
          temperature: 0.7
  mail:
    host: smtp.163.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 25
    default-encoding: UTF-8
    protocol: smtp
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info

notification:
  email:
    receiver: ${NOTIFICATION_EMAIL_RECEIVER}